kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: FCKpDYLR8CT6iwgd+aRQpzSlzLLQMiC1CvzK3VtgQ1g=
      - identity: {}
